# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestClickClearButtonSuccesfully():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_clickClearButtonSuccesfully(self):
    self.driver.get("http://localhost:4200/customer")
    self.driver.set_window_size(1532, 818)
    sleep(2)
    self.driver.find_element(By.ID, "customerId").send_keys("1385")
    self.driver.find_element(By.ID, "nationalityId").send_keys("63527030963")
    sleep(2)
    self.driver.execute_script("window.scrollTo(0, 818)")
    sleep(2)
    clearButton = self.driver.find_element(By.XPATH, "/html/body/app-root/app-customer/app-admin-layout/div/div[2]/app-customer-list/div/div/div[1]/form/div/button[2]")
    sleep(2)
    clearButton.click()
    sleep(2)
    self.driver.execute_script("window.scrollTo(0, 0)")
    sleep(2)
    assert self.driver.find_element(By.ID, "customerId").text == ""

  