# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchFillTheFilterFieldswithDifferentCustomerInformations():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchFillTheFilterFieldswithDifferentCustomerInformations(self):
    self.driver.get("http://localhost:4200/customer")
    self.driver.set_window_size(1552, 840)
    sleep(2)
    self.driver.find_element(By.ID, "customerId").send_keys("1385")
    sleep(1)
    self.driver.find_element(By.ID, "firstName").send_keys("ahmet")
    sleep(1)
    self.driver.execute_script("window.scrollTo(0, 840)")
    sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".customerBtn:nth-child(1)").click()
    sleep(10)
    
    createButton = self.driver.find_element(By.CSS_SELECTOR, ".customerBtn:nth-child(4)")
    assert createButton.text == "CREATE"
