# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginForgotPasswordUnsuccesfully():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_ForgotPasswordUnsuccesfully(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1532, 818)
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customForgoPassword").click()
    sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("sdfsdf@etiya.com")
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".forgotCustomBtn:nth-child(1)").click()
    sleep(2)    
    errorMessage=self.driver.find_element(By.XPATH,"/html/body/app-root/app-forgot-password/div/div/form/div[3]/span")
    assert errorMessage.text=="Invalid e-mail address,please check."



  
