# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginCharacterTypeAndLimitSuccesfully():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginCharacterTypeAndLimitSuccesfully1(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1530, 815)
    self.driver.find_element(By.ID, "email").send_keys("%+&+%&ldfkg3453@etiya.com")
    sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("()4345345fghfghfgh")
    sleep(2)
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "password").clear()
    sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("65465456464@etiya.com")
    sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("dfgdfgdfgdfg")
    sleep(2)
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "password").clear()
    sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("serap@etiya.com")
    sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("serap!ETIYA")
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customBtn").click()
    sleep(2)
    assert self.driver.current_url == "http://localhost:4200/customer"
  
