# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginEnterncorrectandLeaveBlankUnsuccesfully():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_leaveBlankEmailAndPassword(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1530, 815)
    sleep(2)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").click()
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customBtn").click()

    sleep(2)
    errorMessage = self.driver.find_element(By.XPATH, "/html/body/app-root/app-login/div/div/form/div[4]/span")
    assert errorMessage.text == "Invalid username, or password"

  def test_leaveBlankEmailFillPassword(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1530, 815)
    sleep(2)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").send_keys("Busra2154.")
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customBtn").click()
    sleep(2)
    errorMessage = self.driver.find_element(By.XPATH, "/html/body/app-root/app-login/div/div/form/div[4]/span")
    assert errorMessage.text == "Invalid username, or password"

  def test_leaveBlankPasswordFillEmail(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1530, 815)
    sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("serap@etiya.com")
    self.driver.find_element(By.ID, "password").click()
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customBtn").click()
    sleep(2)
    errorMessage = self.driver.find_element(By.XPATH, "/html/body/app-root/app-login/div/div/form/div[4]/span")
    assert errorMessage.text == "Invalid username, or password"

  def test_validFormatButUnvalidData(self):
    self.driver.get("http://localhost:4200/")
    self.driver.set_window_size(1530, 815)
    sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("dfgsdf@etiya.com")
    self.driver.find_element(By.ID, "password").send_keys("Adfgdf4564.")
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".customBtn").click()
    sleep(2)
    errorMessage = self.driver.find_element(By.XPATH, "/html/body/app-root/app-login/div/div/form/div[4]/span")
    assert errorMessage.text == "Invalid username, or password"


